---
functional:
  - Пользователь должен иметь возможность создать учетную запись
  - Пользователь должен иметь возможность входить в свою учетную запись
  - Пользователь должен иметь возможность выйти из своей учетной записи
  - Пользователь должен иметь возможность привязать к своей учетной записи свой профиль GitHub и Discord
  - Пользователь должен иметь возможность выбрать язык программирования, которым будет пользоваться
  - Пользователь должен иметь возможность редактировать свою учетную запись
  - Пользователь должен иметь возможность просматривать таблицу пользовательского рейтинга на сайте
  - Пользователь должен иметь возможность просматривать учетные записи других людей
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность принимать участие в турнирах
  - Пользователь должен иметь возможность добавлять друзей
  - Пользователь должен иметь возможность создавать приватную игру с другом
  - Пользователь должен иметь возможность принимать приглашение на участие в приватной игре с другом
  - Пользователь должен иметь возможность создавать игру с ботом
  - Пользователь должен иметь возможность пригласить в игру другого пользователя
  - Пользователь должен иметь возможность выбирать сложность задачи для игры
  - Пользователь должен иметь возможность выбирать задачу для игры 
  - Пользователь должен иметь возможность выбирать время отведенное на решение задачи
  - Пользователь должен иметь возможность воспроизвести свой код в игре для решения задачи
  - Пользователь должен иметь возможность отправлять сообщения в общем чате лобби
  - Пользователь должен иметь возможность отправлять приватные сообщения другому пользователю
  - Пользователь должен иметь возможность следить за игрой других пользователей
  - Пользователь должен иметь возможность просматривать историю сыгранных игр
  - Пользователь должен иметь возможность сдаться в игре
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте должно отображаться количество пользователей находящихся онлайн
